# Generated by Django 4.1.4 on 2022-12-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                ("customer_name", models.CharField(max_length=20)),
                (
                    "purchase_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("amount_of_product_purchased", models.IntegerField()),
                ("contact_no", models.IntegerField(unique=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
